### ISSUE TITLE
"ValueError: not enough values to unpack (expected 2, got 1)"

### ISSUE THREAD

**Issue by twisp007** [eliranwong/bible-verse-parser#1]
I used the sample file provided and it's not working even with that file.

```
python BibleVerseParser.py dictionary-for-testing.txt
Traceback (most recent call last):
  File "BibleVerseParser.py", line 264, in <module>
    parser = BibleVerseParser(standardisation)
  File "BibleVerseParser.py", line 60, in __init__
    self.updateStandardAbbreviation()
  File "BibleVerseParser.py", line 89, in updateStandardAbbreviation
    self.checkConfig()
  File "BibleVerseParser.py", line 99, in checkConfig
    name, value = ("standardAbbreviation = ", config.standardAbbreviation),
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by twisp007** [comment]
The issue seems to be
`name, value = ("standardAbbreviation = ", config.standardAbbreviation),`
this works
`name, value = ("standardAbbreviation = ", config.standardAbbreviation)`

Also need to import a module
`import pprint`
